
version: "3.9"

services:
  mysql:
    container_name: "ethmysql"
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3306:3306"
    restart: always
    privileged: true
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./data/mysql/data:/var/lib/mysql"
      - "./config/mysql/conf/my.cnf:/etc/my.cnf"
      - "./config/mysql/init:/docker-entrypoint-initdb.d/"
    networks:
      - meta

  execute-1:
    image: tscel/geth:v1.13-base-v5
    container_name: execute-1
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "10000:8551"
      - "11000:8545"
    volumes:
      - ./config:/root/config
      - ./data/execute-1:/root/gethdata
    networks:
      - meta

  attacker-1:
    image: tscel/attacker-v5
    container_name: attacker-1
    entrypoint: /usr/local/bin/attacker.sh
    environment:
      - NAME=attacker-1

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "12000:10000"
      - "12100:10001"
    volumes:
      - ./config/attacker-config.toml:/root/config.toml
      - ./config/strategy-empty.json:/root/strategy.json
      - ./data/attacker-1:/root/attackerdata
    depends_on:
      - mysql
    networks:
      meta:
        ipv4_address: 172.99.1.150

  beacon-1:
    image: tscel/beacon-v5.0.1-t1:0627
    container_name: beacon-1
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmQDMFQcKYKt2oTPS4uvYDbGxp3S8t7oGyd8maCSq2vSCV  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAm9XmGsj5GVuACMVZ2zNiJJw3GMngjYtNrJzLDEGWHQoCU  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAmQqks3Wz9D3VomWeKRqTASod9nzFKPr5HhHFbmW5svFvC  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmFQEWfHEx24doiC6U2Xhj9XMoT2Nsd2oneGAkDkDLJMww 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=0692f57d5ddf34d0f2649d968bf82e2dda69d1f435a7f3a7a26d81a1a11e687b

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13000:4000"
      - "14000:3500"
    volumes:
      - ./config:/root/config
      - ./data/beacon-1:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.2

  beacon-2:
    image: tscel/beacon-v5.0.1-t1:0627
    container_name: beacon-2
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDaSUVFJ2yKW3zfagjSUxp9kz9EG8bQWa5P8HAGE2evD5  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAm9XmGsj5GVuACMVZ2zNiJJw3GMngjYtNrJzLDEGWHQoCU  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAmQqks3Wz9D3VomWeKRqTASod9nzFKPr5HhHFbmW5svFvC  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmFQEWfHEx24doiC6U2Xhj9XMoT2Nsd2oneGAkDkDLJMww 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=9edcc99209261dfca0d5b79cd1ff43e2e30005c629337d921711bb77fa816dd3

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13001:4000"
      - "14001:3500"
    volumes:
      - ./config:/root/config
      - ./data/beacon-2:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.3

  beacon-3:
    image: tscel/beacon-v5.0.1-t1:0627
    container_name: beacon-3
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDaSUVFJ2yKW3zfagjSUxp9kz9EG8bQWa5P8HAGE2evD5  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmQDMFQcKYKt2oTPS4uvYDbGxp3S8t7oGyd8maCSq2vSCV  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAmQqks3Wz9D3VomWeKRqTASod9nzFKPr5HhHFbmW5svFvC  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmFQEWfHEx24doiC6U2Xhj9XMoT2Nsd2oneGAkDkDLJMww 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=9513c7244d2983d47b54df161a3fc981b946944d7c2bba338588e0ab7dc40777

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13002:4000"
      - "14002:3500"
    volumes:
      - ./config:/root/config
      - ./data/beacon-3:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.4

  beacon-4:
    image: tscel/beacon-v5.0.1-t1:0627
    container_name: beacon-4
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDaSUVFJ2yKW3zfagjSUxp9kz9EG8bQWa5P8HAGE2evD5  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmQDMFQcKYKt2oTPS4uvYDbGxp3S8t7oGyd8maCSq2vSCV  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAm9XmGsj5GVuACMVZ2zNiJJw3GMngjYtNrJzLDEGWHQoCU  --peer /ip4/172.99.1.6/tcp/13000/p2p/16Uiu2HAmFQEWfHEx24doiC6U2Xhj9XMoT2Nsd2oneGAkDkDLJMww 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=c118a256c6aa383b0d02a6ac25139566bc042c837f248e71aa38fcd961dac8aa

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13003:4000"
      - "14003:3500"
    volumes:
      - ./config:/root/config
      - ./data/beacon-4:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.5

  beacon-5:
    image: tscel/beacon-v5.0.1-t1:0627
    container_name: beacon-5
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - ALLPEERS= --peer /ip4/172.99.1.2/tcp/13000/p2p/16Uiu2HAmDaSUVFJ2yKW3zfagjSUxp9kz9EG8bQWa5P8HAGE2evD5  --peer /ip4/172.99.1.3/tcp/13000/p2p/16Uiu2HAmQDMFQcKYKt2oTPS4uvYDbGxp3S8t7oGyd8maCSq2vSCV  --peer /ip4/172.99.1.4/tcp/13000/p2p/16Uiu2HAm9XmGsj5GVuACMVZ2zNiJJw3GMngjYtNrJzLDEGWHQoCU  --peer /ip4/172.99.1.5/tcp/13000/p2p/16Uiu2HAmQqks3Wz9D3VomWeKRqTASod9nzFKPr5HhHFbmW5svFvC 
      - EXECUTE=execute-1
      - MAXPEERS=70
      - P2PKEY=f01cd004ad47970f7ca62dadb1921a173c9686cf11e963c04d8a81f36322fd9f

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "13004:4000"
      - "14004:3500"
    volumes:
      - ./config:/root/config
      - ./data/beacon-5:/root/beacondata
    depends_on:
      - execute-1
    networks:
      meta:
        ipv4_address: 172.99.1.6

  validator-1:
    image: tscel/validator-v5.0.1-t1:0627
    container_name: validator-1
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=85
      - VALIDATORS_INDEX=0
      - BEACONRPC=beacon-1:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
      - ./data/validator-1:/root/validatordata
    depends_on:
      - beacon-1
    networks:
      - meta

  validator-2:
    image: tscel/validator-v5.0.1-t1:0627
    container_name: validator-2
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=85
      - BEACONRPC=beacon-2:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
      - ./data/validator-2:/root/validatordata
    depends_on:
      - beacon-2
    networks:
      - meta

  validator-3:
    image: tscel/validator-v5.0.1-t1:0627 
    container_name: validator-3
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=136
      - BEACONRPC=beacon-3:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
      - ./data/validator-3:/root/validatordata
    depends_on:
      - beacon-3
    networks:
      - meta

  validator-4:
    image: tscel/validator-v5.0.1-t1:0627
    container_name: validator-4
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=187
      - BEACONRPC=beacon-4:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
      - ./data/validator-4:/root/validatordata
    depends_on:
      - beacon-4
    networks:
      - meta

  validator-5:
    image: tscel/validator-v5.0.1-t1:0627
    container_name: validator-5
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=18
      - VALIDATORS_INDEX=238
      - BEACONRPC=beacon-5:4000

    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
      - ./data/validator-5:/root/validatordata
    depends_on:
      - beacon-5
    networks:
      - meta


networks:
  meta:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
